name: Documentation

on:
  push:
    branches: [main]
    paths:
      - mkdocs.yml
      - 'docs/**'
      - 'src/**'
  pull_request:
    paths:
      - mkdocs.yml
      - 'docs/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install requirements
        run: |
          uv sync --group docs

      - name: Build docs
        if: github.event_name == 'pull_request'
        run: mkdocs build -s

      - name: Publish docs
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: mkdocs gh-deploy

  cookbook-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install
        run: |
          uv sync --group tests --extra all --extra a2a

      - name: Run Jupyter Notebook tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        working-directory: docs/cookbook
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m ipykernel install --user --name=anyagent
          for nb in `ls -1 *.ipynb`; do jupyter execute --kernel_name=anyagent $nb; done
